#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom actuar rztpois
#' @importFrom dplyr %>%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 ylim
#' @importFrom graphics axis
#' @importFrom graphics legend
#' @importFrom graphics lines
#' @importFrom graphics par
#' @importFrom graphics plot
#' @importFrom graphics text
#' @importFrom graphics title
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom grDevices rgb
#' @importFrom methods new
#' @importFrom randomcoloR randomColor
#' @importFrom stats aggregate
#' @importFrom stats rbinom
#' @importFrom stats rexp
#' @importFrom stats rnorm
#' @importFrom stats runif
#' @importFrom stringr str_c
#' @importFrom stringr str_length
#' @importFrom stringr str_match
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_sub
#' @importFrom stringr str_trim
#' @importFrom stringr str_trunc
#' @importFrom utils globalVariables
#' @importFrom utils read.delim
#' @importFrom utils read.table
#' @importFrom utils write.table
#' @importFrom withr defer
#' @importFrom withr local_dir
#' @importFrom withr local_environment
#' @importFrom withr local_options
#' @importFrom withr local_par
## usethis namespace: end
NULL
